// <auto-generated />
namespace Day4WebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class third2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(third2));
        
        string IMigrationMetadata.Id
        {
            get { return "202204101247019_third2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
